export const siteBrand = "Supporters of NHS Orchestras"
export const conductor = "Barney Blough"
export const conductorEmail = "mailto:bloughb@bsd405.org"
export const baseSiteTitle = "SONO - "
export const mainColor = "info"
